export const Questions = [
  {
    prompt: "What is the animal that is forbidden to eat in islamic religion?",
    optionA: "Cows",
    optionB: "Pig",
    optionC: "camel",
    optionD: "no correct answer",
    asnwer: "optionB",
  },
  {
    prompt: "Which of this is arab country?",
    optionA: "turkya",
    optionB: "spain",
    optionC: "syria",
    optionD: "brazil",
    asnwer: "optionC",
  },
  {
    prompt: "Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
  {
    prompt: "Egypt is located in ??",
    optionA: "australia",
    optionB: "europe",
    optionC: "asia",
    optionD: "africa",
    asnwer: "optionD",
  },
  {
    prompt: "what is smallest arab country in area?",
    optionA: "Egypt",
    optionB: "Bahrin",
    optionC: "Qatar",
    optionD: "Sudan",
    asnwer: "optionB",
  },
  {
    prompt: "Where is the shrine of our master ibrahim,peace be upon him?",
    optionA: "Meccah",
    optionB: "Doha",
    optionC: "Cairo",
    optionD: "Pellestin",
    asnwer: "optionA",
  },
  {
    prompt: "How many players does a basketball team consist of?",
    optionA: "4",
    optionB: "7",
    optionC: "5",
    optionD: "10",
    asnwer: "optionC",
  },
  {
    prompt: "What is the sura located in the middle of the holy qura'n?",
    optionA: "Al-cave",
    optionB: "Al-Israa ",
    optionC: "Al-Naba",
    optionD: "Al-fiel",
    asnwer: "optionA",
  },
  {
    prompt: "What is the thing that was created from stone?",
    optionA: "Saleh's camel",
    optionB: "people'cave",
    optionC: "forces'abraha",
    optionD: "no correct answer",
    asnwer: "optionA",
  },
  {
    prompt: "What is the thing that was preserved from stone?",
    optionA: "Saleh's camel",
    optionB: "people'cave",
    optionC: "forces'abraha",
    optionD: "no correct answer",
    asnwer: "optionB",
  },
];
